name: arcane_admin
description: "Firebase Admin support for Arcane Servers"
version: 1.5.0
repository: https://github.com/ArcaneArts/arcane_admin
environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  fire_api: ">=1.2.0 <2.0.0"
  fire_api_dart: ">=1.2.0 <2.0.0"
  fast_log: ">=1.0.0 <2.0.0"
  google_cloud: ">=0.2.0 <1.0.0"
  googleapis: ">=13.2.0 <15.0.0"
  googleapis_auth: ">=1.6.0 <3.0.0"
  http: ">=1.3.0 <2.0.0"
  googleapis_beta: ">=9.0.0 <10.0.0"
  precision_stopwatch: ">=1.0.0 <2.0.0"
  jose: ">=0.3.4 <1.0.0"
  shelf: ">=1.4.2 <2.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter: